# Generated by Django 4.2.5 on 2023-10-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmparoLegalProceeding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publication_date', models.DateField()),
                ('agreement_date', models.DateField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AmparoTrialCommon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amparo_legal_proceedings', models.ManyToManyField(related_name='amparo_trials', to='Alexandria.amparolegalproceeding')),
            ],
        ),
        migrations.CreateModel(
            name='AmparoTrialTenant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amparo_trial_common', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_amparo_trials', to='Alexandria.amparotrialcommon')),
            ],
        ),
        migrations.CreateModel(
            name='AmparoType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Directo', 'Directo'), ('Indirecto', 'Indirecto')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competencia', models.CharField(max_length=100)),
                ('circuito', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('group_id', models.CharField(max_length=100)),
                ('date_added', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=10)),
                ('azure_blob_url', models.CharField(max_length=200)),
                ('uploaded_date', models.DateField()),
                ('edited_by_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('amparo_trial_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='Alexandria.amparotrialtenant')),
            ],
        ),
        migrations.CreateModel(
            name='LawBranch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Civil', 'Civil'), ('Penal', 'Penal'), ('Laboral', 'Laboral'), ('Familiar', 'Familiar'), ('Mercantil', 'Mercantil'), ('Agrario', 'Agrario'), ('Administrativo', 'Administrativo'), ('Constitucional', 'Constitucional'), ('Contencioso', 'Contencioso'), ('Militar', 'Militar'), ('Propiedad Industrial', 'Propiedad Industrial'), ('Seguridad Social', 'Seguridad Social'), ('Tributario', 'Tributario'), ('Colectivo', 'Colectivo')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LegalParty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('party_type', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('azure_ad_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tenant_legal_proceeding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publication_date', models.DateField()),
                ('agreement_date', models.DateField()),
                ('summary', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_legal_proceedings', to='Alexandria.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=100)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.authority')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.city')),
                ('law_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.lawbranch')),
            ],
        ),
        migrations.CreateModel(
            name='TrialType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, choices=[('Oral', 'Oral'), ('Despido Injustificado', 'Despido Injustificado'), ('Despido Justificado', 'Despido Justificado'), ('Pensión Alimenticia', 'Pensión Alimenticia')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('azure_ad_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Abogado Senior', 'Abogado Senior'), ('Abogado Junior', 'Abogado Junior'), ('Pasante', 'Pasante'), ('Asistente', 'Asistente')], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TrialParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('legal_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.legalparty')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.trial')),
            ],
        ),
        migrations.AddField(
            model_name='trial',
            name='parties',
            field=models.ManyToManyField(through='Alexandria.TrialParty', to='Alexandria.legalparty'),
        ),
        migrations.AddField(
            model_name='trial',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.state'),
        ),
        migrations.AddField(
            model_name='trial',
            name='trial_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.trialtype'),
        ),
        migrations.CreateModel(
            name='TenantTrial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amparo_trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amparo_trial_tenant', to='Alexandria.amparotrialtenant')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tenant_trials', to='Alexandria.user')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_trials', to='Alexandria.customer')),
                ('legal_proceeding_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_tenant_trials', to='Alexandria.tenant_legal_proceeding')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.organization')),
                ('tenant_legal_proceedings', models.ManyToManyField(related_name='m2m_tenant_trials', to='Alexandria.tenant_legal_proceeding')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.trial')),
                ('users', models.ManyToManyField(to='Alexandria.user')),
            ],
        ),
        migrations.AddField(
            model_name='tenant_legal_proceeding',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.tenanttrial'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('amparo_trial_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='Alexandria.amparotrialtenant')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_subscriptions', to='Alexandria.user')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.organization')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.trial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], max_length=10)),
                ('email_status', models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Failed', 'Failed'), ('Opened', 'Opened')], max_length=15, null=True)),
                ('sendgrid_message_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('opened_date', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.organization')),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='Alexandria.trial')),
                ('users', models.ManyToManyField(related_name='notifications', to='Alexandria.user')),
            ],
        ),
        migrations.CreateModel(
            name='LegalProceedingGeneral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publication_date', models.DateField()),
                ('agreement_date', models.DateField()),
                ('summary', models.TextField()),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.trial')),
            ],
        ),
        migrations.CreateModel(
            name='InquerieType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_inqueries', to='Alexandria.user')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.organization')),
            ],
        ),
        migrations.CreateModel(
            name='InqueriesMatter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_inqueries_matters', to='Alexandria.user')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.document')),
                ('inquerie_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.inquerietype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.user')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_documents', to='Alexandria.user'),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant_legal_proceeding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='Alexandria.tenant_legal_proceeding'),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant_trial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='Alexandria.tenanttrial'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_customers', to='Alexandria.user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.organization'),
        ),
        migrations.AddField(
            model_name='customer',
            name='parent_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_customers', to='Alexandria.customer'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.state'),
        ),
        migrations.AddField(
            model_name='authority',
            name='law_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.lawbranch'),
        ),
        migrations.AddField(
            model_name='authority',
            name='parent_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_authorities', to='Alexandria.authority'),
        ),
        migrations.AddField(
            model_name='amparotrialtenant',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_amparo_tenant_trials', to='Alexandria.user'),
        ),
        migrations.AddField(
            model_name='amparotrialtenant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.organization'),
        ),
        migrations.AddField(
            model_name='amparotrialtenant',
            name='users',
            field=models.ManyToManyField(to='Alexandria.user'),
        ),
        migrations.CreateModel(
            name='AmparoTrialParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('amparo_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.amparotrialcommon')),
                ('legal_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.legalparty')),
            ],
        ),
        migrations.AddField(
            model_name='amparotrialcommon',
            name='amparo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.amparotype'),
        ),
        migrations.AddField(
            model_name='amparotrialcommon',
            name='parties',
            field=models.ManyToManyField(through='Alexandria.AmparoTrialParty', to='Alexandria.legalparty'),
        ),
        migrations.AddField(
            model_name='amparotrialcommon',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amparo_trials', to='Alexandria.trial'),
        ),
        migrations.AddField(
            model_name='amparolegalproceeding',
            name='amparo_trial_common',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alexandria.amparotrialcommon'),
        ),
    ]
